### ISSUE TITLE
Status of the Syncthing package for YunoHost

### ISSUE THREAD

**Issue by amuuza** [YunoHost-Apps/syncthing_ynh#10]
Hi!
This is not really an issue. Just wanted to ask what the current status of Syncthing for YunoHost is.
Thank you!

**Comment by tuxmouraille** [comment]
Hello,
The package is working but not maintained, because I don't have free time to work on.
I need some one to tack this project.

Regards

**Comment by frju365** [comment]
I will try to update a bit the package next week.... but if someone want to help me, it could be very very nice.

**Comment by arthurlutz** [comment]
As a user of syncthing I'd be interrested in this app too.

**Comment by jodumont** [comment]
@tuxmouraille and @frju365 
I would like to take over / help to maintain it
It is possible to have a status on where it is
like what is done, what need to be done and where was the focus before your lack of time ?

Regards!

**Comment by tuxmouraille** [comment]
Hello,
@jodumont 
The first step to do is to migrate the package to the last Younohost package specification.
The package use only one instance for all users, it could be better to have an instance for each one.

**Comment by yalh76** [comment]
I started to work on applying last Yunohost package in #12

**Comment by yalh76** [comment]
PR #12 is ready to be tested

**Comment by yalh76** [comment]
Back maintained, open to any contribution
