### ISSUE TITLE
systemd start syncthing failing

### ISSUE THREAD

**Issue by olivier-saugeon** [YunoHost-Apps/syncthing_ynh#124]
### Describe the bug

*systemd start syncthing is failing* when installing the application.

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.0.9.9
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *syncthing 1.20.4~ynh1*

### Steps to reproduce

 ```sh
sudo yunohost app install syncthing
```
the installation is waiting forever at step *Fixing listening service...*

### Investigations

- After some investigations on the running processes, I found that it was blocked when trying to `systemd start syncthing` (line 143 of install script)
- After some comparison of syncthing systemd configuration files from Syncthing (https://github.com/syncthing/syncthing/blob/main/etc/linux-systemd/system/syncthing%40.service) and from Yunohost (https://github.com/YunoHost-Apps/syncthing_ynh/blob/master/conf/systemd.service) I've seen that the one from Yunohost has something which looks like a circular dependency on `multi-user.target`.
- I have made a modified version of the application by removing `multi-user.target` from the `After` field, and successfully installed it.

So, the previously described solution worked for me (RPi, one instance of syncthing) but I'm not sure at all if it is compatible for all possible use cases...

**Comment by Tagadda** [comment]
Can you share the full logs using yunopaste ?
