### ISSUE TITLE
Upgrade Error - No Such Host

### ISSUE THREAD

**Issue by bettyvschmartz** [YunoHost-Apps/syncthing_ynh#138]
### Describe the bug

There is a consistent error in the Syncthing logs complaining that the Syncthing upgrade path/URL cannot be found. 

### Context

- YunoHost version: 11.1
- I have access to my server: through SSH and via Web UI

### Steps to reproduce

Within the Syncthing Web UI open Action > Logs, and see the error.

### Expected behavior

The URL to be available or to be removed, or better error handling. I guess the real upgrade URL of `upgrades.syncthing.net` has been purposefully modified so that in-app upgrades aren't possible. If that's the case maybe pointing to a local meta.json that can be locally controlled would be better, with no error. 

### Logs

The error itself;

`Couldn't fetch release information: Get "https://upgrades1.syncthing.net/meta.json": dial tcp: lookup upgrades1.syncthing.net on 127.0.0.1:53: no such host`

-- bvs

**Comment by yalh76** [comment]
You will need to manually fix it in the `/var/www/syncthing/.config/syncthing/config.xml` replacing `upgrades1.syncthing.net` to `upgrades.syncthing.net`
