### ISSUE TITLE
Using existing folder

### ISSUE THREAD

**Issue by IsidoreIsou** [YunoHost-Apps/syncthing_ynh#20]
Hello,

I am trying to add an existing folder to Syncthing:
`/home/yunohost.multimedia/thomas`

but it returns an error, since it needs permissions:
```
2019-06-25 17:27:41: Failed to create folder marker: mkdir /home/yunohost.multimedia/thomas/.stfolder: permission denied
2019-06-25 17:27:41: Error on folder "Multimedia" (hxxmw-rdjhw): folder marker missing
```
I've try to add the user `syncthing` to the group `multimedia` but no success.
Would you know how to solve it?
I've asked about it on the YNH forum as well, will update both.

**Comment by IsidoreIsou** [comment]
Solved!
```
setfacl -Rm user:syncthing:rwx /home/yunohost.multimedia/thomas
```

**Comment by qwertz098** [comment]
@IsidoreIsou May you open the issue? I ran into the same and think it'd just work out of the box and be configured during installation.

**Comment by yalh76** [comment]
> 
> 
> @IsidoreIsou May you open the issue? I ran into the same and think it'd just work out of the box and be configured during installation.

Well it works out of the box: 
1. A dedicated folder is defined:
https://github.com/YunoHost-Apps/syncthing_ynh/blob/a351c2b6431a3ac092f3581a9778a402ec81f963/scripts/install#L35-L36
2. The folder is created and right for syncthing are put on that folder:
https://github.com/YunoHost-Apps/syncthing_ynh/blob/a351c2b6431a3ac092f3581a9778a402ec81f963/scripts/install#L107-L109
3. Syncthing is configured to use that folder as default folder:
https://github.com/YunoHost-Apps/syncthing_ynh/blob/a351c2b6431a3ac092f3581a9778a402ec81f963/scripts/install#L119-L129
https://github.com/YunoHost-Apps/syncthing_ynh/blob/a351c2b6431a3ac092f3581a9778a402ec81f963/conf/config.xml#L45

> Acces should be aloowed to one's own home folder and that shared yunohost data folder(s).

I've no opinion on that point but feel free to do a PR.

**Comment by quartztester** [comment]
To anyone coming here in the future - it's a rather security ill prone solution but here is what I used.

`chmod -R 777 /home/yunohost.app/syncthing`

This will give next cloud the ability to see the syncthing folder when you connect it as an external storage within Nextcloud in my case. Keep in mind the limitation of this method.

Further reading: https://stackoverflow.com/questions/8328481/chmod-777-to-a-folder-and-all-contents
