### ISSUE TITLE
https://127.0.0.1/ after enable https for GUI

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/syncthing_ynh#37]
When enabling HTTPS for GUI (in settings > GUI) the website is not available/reachable any more -> https://127.0.0.1/
![Screenshot_2020-02-25 aksel rocks Syncthing](https://user-images.githubusercontent.com/44803148/75222881-891fbb80-57a5-11ea-8dbf-4c03e0066314.png)

**Comment by yalh76** [comment]
You don't need to activate https, https is already managed by YunoHost
You have to look at /var/www/syncthing/.config/syncthing/config.xml, the parameter you changed might be there.
