### ISSUE TITLE
Could not complete the operation 'Install the 'syncthing' app'. 

### ISSUE THREAD

**Issue by strasbourgcurieux** [YunoHost-Apps/syncthing_ynh#40]
Bonjour

Le message
"
Could not complete the operation 'Install the 'syncthing' app'. Please provide the full log of this operation by clicking here to get help
"

Les Log
https://paste.yunohost.org/raw/aqeseyohun

YunoHost 3.7.0.12 (stable). 
Debian 9.12 32bit (Linux 4.9.0-12-686)       

Cordialement

**Comment by yalh76** [comment]
There was an error on a file name. it's now solved you can try to install
