### ISSUE TITLE
Synced folders are not backed up

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/syncthing_ynh#49]
**Describe the bug**
Folders synced with syncthing are not put into the automatic yunohost backups

**Versions**
- Hardware: VPS bought online
- YunoHost version: 3.8.4.8
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.6.1~ynh1

**To Reproduce**
1. Create a synced folder using the web interface
2. Connect an external device to it
3. Sync some files to the server
4. Perform a yunohost backup with `yunohost backup create`
5. The files synced with syncthing are not included in the backups

**Expected behavior**
The data of the synced folders should be included in the backups

**Comment by yalh76** [comment]
Thanks for the report.
The points are:
- The goal of the backup is to mainly backup the app itself. 
- Including the synced files could cause very huge backups.

**Comment by kuba-orlik** [comment]
Thank you for the answer. It seems I wrongly assumed that the data should be backed up, as well. It might reveal a different issue, namely: it wasn't clear to me that the data wouldn't be included in the backups. 

I'm using a customized backup solution, anyway, so I'll just add the data folders to them

**Comment by yalh76** [comment]
Well, most of app include datas during backup if the data are stored in the database or in the app folder. But for syncthing, like it's done for nextcloud, datas are stored in : https://github.com/YunoHost-Apps/syncthing_ynh/blob/b46834a4a219fbcfc455320181e372ffe8348032/scripts/install#L34

Assuming that each YunoHost admin manage the backup of `/home`

**Comment by kuba-orlik** [comment]
So if I choose the folder location to be within `/home/yunohost.app/syncthing`, then the data will be put in the backups?

**Comment by yalh76** [comment]
No they won't be backuped, the content of `/home/yunohost.app/syncthing` is not backuped during syncthing backup
