### ISSUE TITLE
'app is still using the skipped/protected/unprotected_uris/regex settings'

### ISSUE THREAD

**Issue by Spacesurfer** [YunoHost-Apps/syncthing_ynh#61]
**Describe the bug**
Get the error message shown below when installing Syncthing for the first time. 

**Versions**
- Hardware: *Librem Mini (Intel i5-8250)*
- YunoHost version: 4.1.7.1 (stable)
- Syncthing Version 1.12.0~ynh1
- I have access to my server: *through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*

**To Reproduce**
*Installed from webadmin, and it showed in the output at the top as Syncthing was installing*

**Expected behavior**
That the package is updated with the updated permissions scheme on Yunohost.

**Logs**
/!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

**Comment by yalh76** [comment]
syncthing has been moved to the new permission system
