### ISSUE TITLE
Move to YunoHost-Apps?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/syncthing_ynh#9]
Hello
I really like your package. I used it years ago but stopped for some reason. I wanted to install it again and saw your recent changes
Would you mind moving the app to the yunohost-apps organisation please? https://github.com/YunoHost-Apps

It might give more visibility to the app and allow for collaborative improvements

Thanks

**Comment by tuxmouraille** [comment]
Hello,
I updated the package to correct some bugs, as is it works.
I 'm working to make it multi-instance, and fully compatible with Yunohost package format.

I agree to move. How I have to do it?

Thanks

**Comment by frju365** [comment]
You must change the owner of the repository : Settings < Transfer Ownership. The new owner must be "Yunohost-Apps". Don't worry, you will keep write access.

Thanks.

**Comment by tuxmouraille** [comment]
Hello,
You need to create a new team to I transfer the project to.

**Comment by tuxmouraille** [comment]
Transferred to Yunohost-Apps.

Thanks

**Comment by frju365** [comment]
Thanks.  Don't hesitate to ask any question on the forum, XMPP, IRC or Matrix, and to the group Dev or Apps if you have any problem or if you want any suggestion. You can help us too... or try to package new apps ;-) 

 I close this issue.
