### ISSUE TITLE
How to make it work with /home/yunohost.app and the like

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/syncthing_ynh#98]
I'd like to try and use it as a backup solution for the home folder (yunohost). I added the "syncthing" user to the root and other such groups, but it still says it does not have permission to access the folder.

**Comment by lil5** [comment]
Adding groups require a logout-login or restart to take effect.

**Comment by tio-trom** [comment]
Ah ok makes sense I will try thanks!
